name: Cyber behaviour profiling - .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    # Create a directory to store all our logs
    - name: Create Logs Directory
      run: mkdir logs -Force

    - name: Initialize CodeQL 
      uses: github/codeql-action/init@v3
      with:
        languages: csharp
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore Cyber-behaviour-profiling.sln | Tee-Object -FilePath logs/restore.log

    - name: Software Composition Analysis (SCA)
      run: dotnet list package --vulnerable --include-transitive | Tee-Object -FilePath logs/sca.log

    - name: Lint Code
      run: dotnet format Cyber-behaviour-profiling.sln --verify-no-changes | Tee-Object -FilePath logs/lint.log

    - name: Build project
      run: dotnet build Cyber-behaviour-profiling.sln --no-restore --configuration Release | Tee-Object -FilePath logs/build.log

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    - name: Run Unit Tests
      run: dotnet test Cyber-behaviour-profiling.sln --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=test_results.trx" | Tee-Object -FilePath logs/test.log

    - name: Upload Pipeline Logs
      if: always() 
      uses: actions/upload-artifact@v3
      with:
        name: pipeline-run-logs
        path: |
          logs/
          **/*.trx